In [1]:
import os
import pickle
import json
import glob
import numpy as np
import networkx as nx
import time
import pandas as pd
pd.set_option("display.max_columns", 100)

In [ ]:
### pull prim repo to somewhere in HAL 

In [2]:
!pwd

/home/iferwna/irm_access


In [3]:
%cd ../../shared/irm/genome_vision_data/MetaShift/

/home/shared/irm/genome_vision_data/MetaShift


### Domain generalization experiment example

In [ ]:
!python run_main.py --algorithm IRM --details 'test_experiment_II' --pyfile 'experiments/distribution_shift/main_experiment.py' --data 'data/main_experiment_test_data' --dataset_script 'dataset/create_domain_generalization_dataset.py --seed 130 --minority_percentage 1 --overlap_len 0' --anneals_p1 500 --anneals_p2 100 --anneals_irm 100


EXPERIMENT LIST:  ['p1', 'p2', 'irm']
Domain Generalization folder:  data/main_experiment_test_data_seed_42
pickle load 17938 dataset/meta_data/full-candidate-subsets.pkl
Done! Please check  data/MetaShift/MetaDataset-full
ground
chair
suitcase
floor
book
table
bowl
water
wall
bag
sheet
toy
bed
pillow
carpet
mirror
door
person
fence
woman
man
animal
grass
collar
hat
comforter
blanket
pillows
food
plate
cell phone
curtain
lamp
window
bottle
cup
bike
seat
car
motorcycle
backpack
rug
bookshelf
container
dog
bird
shower curtain
lady
picture
couch
blinds
sink
faucet
remote control
keyboard
books
box
screen
computer
cabinet
monitor
papers
glasses
laptop
counter
bench
television
shelf
toilet
toilet paper
towel
paper
house
candle
roof
umbrella
bicycle
ball
girl
luggage
vase
mat
drawer
refrigerator
desk
clock
speaker
tissue
teddy bear
pot
sofa
camera
computer mouse
napkin
boy
bear
entertainment center
coffee table
horse
phone
dvd player
bookcase
purse
length:  81
['ground', 'chair', 'suitcase',

spectral clustering: 
quality:  0.2413001275785966
spectral clustering: 
quality:  0.14334898873375868
spectral clustering: 
quality:  0.14876138361754865
number of communities in env 1:  40 10
number of communities in env 2 23 6
[array(['book', 'sofa', 'phone', 'cabinet', 'clock', 'pot', 'vase', 'bowl',
       'cup', 'container', 'desk', 'rug', 'refrigerator', 'toilet', 'toy',
       'mat', 'curtain', 'window', 'shelf', 'screen', 'picture', 'chair',
       'food', 'table', 'towel', 'coffee table', 'monitor', 'plate',
       'keyboard', 'television', 'books', 'bottle', 'carpet',
       'cell phone', 'drawer', 'door', 'suitcase', 'wall', 'box',
       'laptop'], dtype='<U14'), array(['lamp', 'remote control', 'pillows', 'couch', 'pillow',
       'comforter', 'teddy bear', 'bed', 'blanket', 'sheet'], dtype='<U14')]
[array(['boy', 'animal', 'fence', 'ground', 'woman', 'bicycle', 'bag',
       'water', 'girl', 'bird', 'man', 'hat', 'purse', 'collar', 'person',
       'ball', 'umbrella', 'g

spectral clustering: 
quality:  0.24130012757859687
spectral clustering: 
quality:  0.1563146013807988
spectral clustering: 
quality:  0.16276225348104723
number of communities in env 1:  38 12
number of communities in env 2 7 22
[array(['screen', 'rug', 'plate', 'keyboard', 'food', 'cell phone',
       'clock', 'book', 'coffee table', 'drawer', 'container', 'mat',
       'desk', 'books', 'table', 'television', 'vase', 'picture',
       'window', 'bottle', 'door', 'toilet', 'laptop', 'wall', 'toy',
       'towel', 'shelf', 'curtain', 'chair', 'monitor', 'phone',
       'cabinet', 'bowl', 'carpet', 'pot', 'cup', 'box', 'refrigerator'],
      dtype='<U14'), array(['sheet', 'sofa', 'lamp', 'comforter', 'suitcase', 'bed', 'blanket',
       'pillows', 'couch', 'pillow', 'teddy bear', 'remote control'],
      dtype='<U14')]
[array(['bicycle', 'motorcycle', 'car', 'mirror', 'camera', 'seat', 'bike'],
      dtype='<U10'), array(['backpack', 'glasses', 'hat', 'bag', 'ball', 'fence', 'person',
 

spectral clustering: 
quality:  0.24130012757859515
spectral clustering: 
quality:  0.14334898873375818
spectral clustering: 
quality:  0.1627622534810474
number of communities in env 1:  40 10
number of communities in env 2 22 7
[array(['curtain', 'bowl', 'pot', 'shelf', 'container', 'keyboard',
       'clock', 'refrigerator', 'monitor', 'picture', 'wall',
       'coffee table', 'toy', 'window', 'drawer', 'sofa', 'cell phone',
       'cabinet', 'screen', 'plate', 'towel', 'food', 'table', 'book',
       'cup', 'vase', 'suitcase', 'laptop', 'toilet', 'door', 'desk',
       'rug', 'mat', 'chair', 'bottle', 'books', 'phone', 'box', 'carpet',
       'television'], dtype='<U14'), array(['lamp', 'comforter', 'pillows', 'couch', 'pillow', 'sheet',
       'remote control', 'blanket', 'teddy bear', 'bed'], dtype='<U14')]
[array(['collar', 'bench', 'purse', 'bag', 'ground', 'house', 'backpack',
       'horse', 'person', 'fence', 'water', 'woman', 'girl', 'umbrella',
       'hat', 'glasses', 'ma

accuracy 0.730 	 roc_auc_score 0.846
confusion_matrix
[[56 44]
 [10 90]]
classification_report
              precision    recall  f1-score   support

           0       0.85      0.56      0.67       100
           1       0.67      0.90      0.77       100

    accuracy                           0.73       200
   macro avg       0.76      0.73      0.72       200
weighted avg       0.76      0.73      0.72       200

VAL * Acc@1 73.000
 * Acc@1 73.000 Acc@5 0.000
accuracy 1.000 	 size: 50 	 dog_p1_test
accuracy 0.800 	 size: 50 	 dog_p0_test
accuracy 0.700 	 size: 50 	 cat_p0_test
accuracy 0.420 	 size: 50 	 cat_p1_test
group keys:  dict_keys(['p0', 'p1'])
accuracy 0.750 	 roc_auc_score 0.848 	 size: 100  	 p0 
accuracy 0.710 	 roc_auc_score 0.898 	 size: 100  	 p1 
--seed 1
Environment:
	Python: 3.8.0
	PyTorch: 1.7.1
	Torchvision: 0.8.2
	CUDA: 11.0
	CUDNN: 8004
	NumPy: 1.19.2
	PIL: 8.3.1
Args:
	algorithm: IRM
	anneal: 500.0
	batch_size: 8
	data: data/main_experiment_test_data_seed_43

Iteration: 0
out-of-domain val
accuracy 0.502 	 roc_auc_score 0.470
confusion_matrix
[[324   5]
 [323   6]]
classification_report
              precision    recall  f1-score   support

           0       0.50      0.98      0.66       329
           1       0.55      0.02      0.04       329

    accuracy                           0.50       658
   macro avg       0.52      0.50      0.35       658
weighted avg       0.52      0.50      0.35       658

VAL * Acc@1 50.152
 * Acc@1 50.152 Acc@5 0.000
accuracy 1.000 	 size: 21 	 cat_p1_val
accuracy 0.984 	 size: 308 	 cat_p0_val
accuracy 0.095 	 size: 21 	 dog_p1_val
accuracy 0.013 	 size: 308 	 dog_p0_val
group keys:  dict_keys(['p0', 'p1'])
accuracy 0.548 	 roc_auc_score 0.510 	 size: 42  	 p1 
accuracy 0.498 	 roc_auc_score 0.468 	 size: 616  	 p0 
Iteration: 20
out-of-domain val
accuracy 0.816 	 roc_auc_score 0.910
confusion_matrix
[[247  82]
 [ 39 290]]
classification_report
              precision    recall  f1-score   support

    

Iteration: 40
out-of-domain val
accuracy 0.847 	 roc_auc_score 0.919
confusion_matrix
[[ 70  20]
 [ 38 252]]
classification_report
              precision    recall  f1-score   support

           0       0.65      0.78      0.71        90
           1       0.93      0.87      0.90       290

    accuracy                           0.85       380
   macro avg       0.79      0.82      0.80       380
weighted avg       0.86      0.85      0.85       380

VAL * Acc@1 84.737
 * Acc@1 84.737 Acc@5 0.000
accuracy 0.869 	 size: 268 	 dog_p0_val
accuracy 0.864 	 size: 22 	 dog_p1_val
accuracy 0.795 	 size: 78 	 cat_p0_val
accuracy 0.667 	 size: 12 	 cat_p1_val
group keys:  dict_keys(['p0', 'p1'])
accuracy 0.853 	 roc_auc_score 0.920 	 size: 346  	 p0 
accuracy 0.794 	 roc_auc_score 0.913 	 size: 34  	 p1 
Iteration: 60
out-of-domain val
accuracy 0.921 	 roc_auc_score 0.944
confusion_matrix
[[ 67  23]
 [  7 283]]
classification_report
              precision    recall  f1-score   support

    

### extracting results

In [70]:
!python extract_DG_results.py --experiment_name 'test_experiment_II' --results_file_name 'results/test_experiment_II.csv' --data_folder 'data/main_experiment_test_data' --opt
df = pd.read_csv('results/test_experiment_II.csv',index_col=0)  
df

## intersection 1
## intersection 2
{100.0}
{100.0}
final anneals []
final penals [100.0]
minorities at each seed:  [['p_0', 'p_1'], ['p_0', 'p_1'], ['p_0', 'p_0']]


algorithm indoor_p0_acc_val indoor_p1_acc_val indoor_p0_auc_val  \
0     P-IRM       0.845(0.03)       0.861(0.02)       0.931(0.02)   
0       IRM       0.809(0.02)       0.865(0.01)       0.928(0.01)   

  indoor_p1_auc_val indoor_p0_acc_test indoor_p1_acc_test indoor_p0_auc_test  \
0       0.948(0.01)        0.803(0.07)        0.883(0.02)        0.905(0.05)   
0       0.956(0.01)        0.817(0.04)        0.867(0.02)        0.925(0.04)   

  indoor_p1_auc_test outdoor_p0_acc_val outdoor_p1_acc_val outdoor_p0_auc_val  \
0        0.946(0.01)        0.823(0.04)        0.906(0.02)        0.933(0.01)   
0        0.965(0.00)        0.842(0.01)        0.887(0.05)        0.940(0.01)   

  outdoor_p1_auc_val outdoor_p0_acc_test outdoor_p1_acc_test  \
0        0.977(0.01)         0.847(0.01)         0.877(0.04)   
0        0.964(0.02)         0.843(0.03)         0.900(0.02)   

  outdoor_p0_auc_test outdoor_p1_auc_test indoor_avg_acc_val  \
0         0.946(0.02)         0.964(0.03)        0.853(0.02)   
0         0.943(0.01)         0.966(0.01)        0.837(0.01)   

  indoor_avg_auc_val outdoor_avg_acc_val outdoor_avg_auc_val  \
0        0.940(0.02)         0.864(0.02)         0.955(0.00)   
0        0.942(0.01)         0.864(0.02)         0.952(0.01)   

  indoor_avg_acc_test indoor_avg_auc_test outdoor_avg_acc_test  \
0         0.843(0.04)         0.925(0.03)          0.862(0.03)   
0         0.842(0.02)         0.945(0.02)          0.872(0.02)   

  outdoor_avg_auc_test avg_minorirty_acc_val avg_minorirty_auc_val  \
0          0.955(0.01)           0.000(0.00)           0.000(0.00)   
0          0.954(0.00)           0.000(0.00)           0.000(0.00)   

  avg_minorirty_acc_test avg_minorirty_auc_test  avg_acc_val  avg_auc_val  \
0            0.000(0.00)            0.000(0.00)  0.859(0.02)  0.947(0.01)   
0            0.000(0.00)            0.000(0.00)  0.851(0.01)  0.947(0.00)   

  avg_acc_test avg_auc_test  
0  0.853(0.02)  0.940(0.01)  
0  0.857(0.01)  0.950(0.01)

### Subpopulation shift experiment example

In [46]:
!python run_main.py --algorithm IRM --details 'test_experiment_II_subpop' --pyfile 'main_experiment.py' --data 'data/main_experiment_test_data' --dataset_script 'dataset/create_subpopulationshift_dataset.py --seed 130 --minority_percentage 1 --overlap_len 0' --anneals_p1 500 --anneals_p2 100 --anneals_irm 100 --data_exists


EXPERIMENT LIST:  ['p1', 'p2', 'irm']
irm_lambda:  100
--seed 0
Environment:
	Python: 3.8.0
	PyTorch: 1.7.1
	Torchvision: 0.8.2
	CUDA: 11.0
	CUDNN: 8004
	NumPy: 1.19.2
	PIL: 8.3.1
Args:
	algorithm: IRM
	anneal: 500.0
	batch_size: 8
	data: data/main_experiment_test_data_seed_42/p1
	details: test_experiment_II_subpop
	domains: [<_io.TextIOWrapper name='pirm_domains.json' mode='r' encoding='UTF-8'>]
	experiment: pirm
	hparams: None
	hparams_seed: 0
	irm_lambda: 100.0
	log_prefix: 
	lr: 5e-05
	num_classes: 2
	num_domains: 2
	output_dir: train_output
	results_file: results/test_experiment_II_subpop_p1
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	workers: 4
train_dataset.samples reverse: [('cat_p1', 389), ('dog_p1', 389), ('cat_p0', 383), ('dog_p0', 383)]
self.domain_to_groups {'0': {'cat': ['cat_p0'], 'dog': ['dog_p0']}, '1': {'cat': ['cat_p1'], 'dog': ['dog_p1']}}
HParams:
	batch_size: 8
	class_balanced: False
	data_augmentation: True
	irm_lambda: 100.0
	irm_penalt

group keys:  dict_keys(['p0', 'p1'])
accuracy 0.500 	 roc_auc_score 0.588 	 size: 328  	 p0 
accuracy 0.500 	 roc_auc_score 0.600 	 size: 196  	 p1 
Iteration: 20
out-of-domain val
accuracy 0.790 	 roc_auc_score 0.908
confusion_matrix
[[236  26]
 [ 84 178]]
classification_report
              precision    recall  f1-score   support

           0       0.74      0.90      0.81       262
           1       0.87      0.68      0.76       262

    accuracy                           0.79       524
   macro avg       0.81      0.79      0.79       524
weighted avg       0.81      0.79      0.79       524

VAL * Acc@1 79.008
 * Acc@1 79.008 Acc@5 0.000
accuracy 0.959 	 size: 98 	 cat_p1_val
accuracy 0.866 	 size: 164 	 cat_p0_val
accuracy 0.726 	 size: 164 	 dog_p0_val
accuracy 0.602 	 size: 98 	 dog_p1_val
group keys:  dict_keys(['p0', 'p1'])
accuracy 0.796 	 roc_auc_score 0.908 	 size: 328  	 p0 
accuracy 0.781 	 roc_auc_score 0.916 	 size: 196  	 p1 
Iteration: 40
out-of-domain val
accurac

Iteration: 60
out-of-domain val
accuracy 0.866 	 roc_auc_score 0.951
confusion_matrix
[[226  36]
 [ 34 228]]
classification_report
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       262
           1       0.86      0.87      0.87       262

    accuracy                           0.87       524
   macro avg       0.87      0.87      0.87       524
weighted avg       0.87      0.87      0.87       524

VAL * Acc@1 86.641
 * Acc@1 86.641 Acc@5 0.000
accuracy 0.939 	 size: 98 	 cat_p1_val
accuracy 0.890 	 size: 164 	 dog_p0_val
accuracy 0.837 	 size: 98 	 dog_p1_val
accuracy 0.817 	 size: 164 	 cat_p0_val
group keys:  dict_keys(['p0', 'p1'])
accuracy 0.888 	 roc_auc_score 0.972 	 size: 196  	 p1 
accuracy 0.854 	 roc_auc_score 0.941 	 size: 328  	 p0 
Iteration: 80
out-of-domain val
accuracy 0.878 	 roc_auc_score 0.958
confusion_matrix
[[235  27]
 [ 37 225]]
classification_report
              precision    recall  f1-score   support

  

accuracy 0.874 	 roc_auc_score 0.969
confusion_matrix
[[98  5]
 [21 82]]
classification_report
              precision    recall  f1-score   support

           0       0.82      0.95      0.88       103
           1       0.94      0.80      0.86       103

    accuracy                           0.87       206
   macro avg       0.88      0.87      0.87       206
weighted avg       0.88      0.87      0.87       206

VAL * Acc@1 87.379
 * Acc@1 87.379 Acc@5 0.000
accuracy 0.961 	 size: 51 	 cat_p1_val
accuracy 0.942 	 size: 52 	 cat_p0_val
accuracy 0.902 	 size: 51 	 dog_p1_val
accuracy 0.692 	 size: 52 	 dog_p0_val
group keys:  dict_keys(['p1', 'p0'])
accuracy 0.931 	 roc_auc_score 0.993 	 size: 102  	 p1 
accuracy 0.817 	 roc_auc_score 0.935 	 size: 104  	 p0 
accuracy 0.850 	 roc_auc_score 0.952
confusion_matrix
[[93  7]
 [23 77]]
classification_report
              precision    recall  f1-score   support

           0       0.80      0.93      0.86       100
           1       0.9

--seed 2
Environment:
	Python: 3.8.0
	PyTorch: 1.7.1
	Torchvision: 0.8.2
	CUDA: 11.0
	CUDNN: 8004
	NumPy: 1.19.2
	PIL: 8.3.1
Args:
	algorithm: IRM
	anneal: 100.0
	batch_size: 8
	data: data/main_experiment_test_data_seed_44/p2
	details: test_experiment_II_subpop
	domains: [<_io.TextIOWrapper name='pirm_domains.json' mode='r' encoding='UTF-8'>]
	experiment: pirm
	hparams: None
	hparams_seed: 0
	irm_lambda: 100.0
	log_prefix: 
	lr: 5e-05
	num_classes: 2
	num_domains: 2
	output_dir: train_output
	results_file: results/test_experiment_II_subpop_p2
	save_model_every_checkpoint: False
	seed: 2
	skip_model_save: False
	workers: 4
train_dataset.samples reverse: [('cat_p1', 562), ('dog_p1', 562), ('cat_p0', 485), ('dog_p0', 485)]
self.domain_to_groups {'0': {'cat': ['cat_p0'], 'dog': ['dog_p0']}, '1': {'cat': ['cat_p1'], 'dog': ['dog_p1']}}
HParams:
	batch_size: 8
	class_balanced: False
	data_augmentation: True
	irm_lambda: 100.0
	irm_penalty_anneal_iters: 100.0
	lr: 5e-05
	nonlinear_classifier:

accuracy 0.962 	 size: 52 	 dog_outdoor_p0_val
accuracy 0.961 	 size: 51 	 dog_outdoor_p1_val
accuracy 0.939 	 size: 99 	 dog_indoor_p0_val
accuracy 0.939 	 size: 98 	 dog_indoor_p1_val
accuracy 0.194 	 size: 98 	 cat_indoor_p1_val
accuracy 0.176 	 size: 51 	 cat_outdoor_p1_val
accuracy 0.173 	 size: 52 	 cat_outdoor_p0_val
accuracy 0.141 	 size: 99 	 cat_indoor_p0_val
group keys:  dict_keys(['indoor_p0', 'indoor_p1', 'outdoor_p1', 'outdoor_p0'])
accuracy 0.569 	 roc_auc_score 0.789 	 size: 102  	 outdoor_p1 
accuracy 0.567 	 roc_auc_score 0.683 	 size: 104  	 outdoor_p0 
accuracy 0.566 	 roc_auc_score 0.663 	 size: 196  	 indoor_p1 
accuracy 0.540 	 roc_auc_score 0.670 	 size: 198  	 indoor_p0 
Iteration: 20
out-of-domain val
accuracy 0.790 	 roc_auc_score 0.891
confusion_matrix
[[191 109]
 [ 17 283]]
classification_report
              precision    recall  f1-score   support

           0       0.92      0.64      0.75       300
           1       0.72      0.94      0.82       300



HParams:
	batch_size: 8
	class_balanced: False
	data_augmentation: True
	irm_lambda: 100.0
	irm_penalty_anneal_iters: 100.0
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Iteration: 0
out-of-domain val
accuracy 0.531 	 roc_auc_score 0.603
confusion_matrix
[[ 53 320]
 [ 30 343]]
classification_report
              precision    recall  f1-score   support

           0       0.64      0.14      0.23       373
           1       0.52      0.92      0.66       373

    accuracy                           0.53       746
   macro avg       0.58      0.53      0.45       746
weighted avg       0.58      0.53      0.45       746

VAL * Acc@1 53.083
 * Acc@1 53.083 Acc@5 0.000
accuracy 0.969 	 size: 98 	 dog_indoor_p1_val
accuracy 0.929 	 size: 56 	 dog_outdoor_p0_val
accuracy 0.896 	 size: 164 	 dog_indoor_p0_val
accuracy 0.891 	 size: 55 	 dog_outdoor_p1_val
accuracy 0.179 	 size: 56 	 cat_outdoor_p0_val
accuracy 0.165 	 size: 164 	 cat_indoor_p0

	***

Environment:
	Python: 3.8.0
	PyTorch: 1.7.1
	Torchvision: 0.8.2
	CUDA: 11.0
	CUDNN: 8004
	NumPy: 1.19.2
	PIL: 8.3.1
Args:
	algorithm: IRM
	anneal: 100.0
	batch_size: 8
	data: data/main_experiment_test_data_seed_44/irm
	details: test_experiment_II_subpop
	domains: [<_io.TextIOWrapper name='irm_domains.json' mode='r' encoding='UTF-8'>]
	experiment: irm
	hparams: None
	hparams_seed: 0
	irm_lambda: 100.0
	log_prefix: 
	lr: 5e-05
	num_classes: 2
	num_domains: 2
	output_dir: train_output
	results_file: results/test_experiment_II_subpop_irm
	save_model_every_checkpoint: False
	seed: 2
	skip_model_save: False
	workers: 4
train_dataset.samples reverse: [('cat_outdoor_p1', 562), ('dog_outdoor_p1', 562), ('cat_outdoor_p0', 485), ('dog_outdoor_p0', 485), ('cat_indoor_p0', 383), ('dog_indoor_p0', 383), ('cat_indoor_p1', 375), ('dog_indoor_p1', 375)]
self.domain_to_groups {'0': {'cat': ['cat_indoor_p0', 'cat_indoor_p1'], 'dog': ['dog_indoor_p0', 'dog_indoor_p1']}, '1': {'cat': ['cat_outdoor_p0

accuracy 0.845 	 roc_auc_score 0.928
confusion_matrix
[[174  26]
 [ 36 164]]
classification_report
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       200
           1       0.86      0.82      0.84       200

    accuracy                           0.84       400
   macro avg       0.85      0.84      0.84       400
weighted avg       0.85      0.84      0.84       400

VAL * Acc@1 84.500
 * Acc@1 84.500 Acc@5 0.000
accuracy 1.000 	 size: 50 	 cat_outdoor_p1_test
accuracy 0.960 	 size: 50 	 cat_outdoor_p0_test
accuracy 0.940 	 size: 50 	 dog_indoor_p1_test
accuracy 0.880 	 size: 50 	 dog_indoor_p0_test
accuracy 0.860 	 size: 50 	 cat_indoor_p1_test
accuracy 0.760 	 size: 50 	 dog_outdoor_p1_test
accuracy 0.700 	 size: 50 	 dog_outdoor_p0_test
accuracy 0.660 	 size: 50 	 cat_indoor_p0_test
group keys:  dict_keys(['outdoor_p0', 'indoor_p0', 'outdoor_p1', 'indoor_p1'])
accuracy 0.900 	 roc_auc_score 0.960 	 size: 100  	 indoor_p1 
accur

### extracting results

In [67]:
!python extract_DG_results.py --experiment_name 'test_experiment_II_subpop' --results_file_name 'results/test_experiment_II_subpop_ii.csv' --opt --data_folder 'data/main_experiment_test_data'
df = pd.read_csv('results/test_experiment_II_subpop_ii.csv',index_col=0)  
df

## intersection 1
## intersection 2
{100.0}
{100.0}
final anneals []
final penals [100.0]
minorities at each seed:  [['p_1', 'p_0'], ['p_1', 'p_0'], ['p_0', 'p_0']]


algorithm indoor_p0_acc_val indoor_p1_acc_val indoor_p0_auc_val  \
0     P-IRM       0.845(0.02)       0.867(0.01)       0.932(0.02)   
0       IRM       0.819(0.03)       0.860(0.00)       0.929(0.02)   

  indoor_p1_auc_val indoor_p0_acc_test indoor_p1_acc_test indoor_p0_auc_test  \
0       0.951(0.01)        0.807(0.06)        0.880(0.02)        0.907(0.05)   
0       0.954(0.01)        0.813(0.03)        0.887(0.01)        0.924(0.04)   

  indoor_p1_auc_test outdoor_p0_acc_val outdoor_p1_acc_val outdoor_p0_auc_val  \
0        0.947(0.01)        0.830(0.03)        0.912(0.03)        0.936(0.00)   
0        0.963(0.00)        0.842(0.02)        0.877(0.06)        0.946(0.01)   

  outdoor_p1_auc_val outdoor_p0_acc_test outdoor_p1_acc_test  \
0        0.978(0.01)         0.850(0.02)         0.880(0.04)   
0        0.963(0.02)         0.850(0.02)         0.880(0.02)   

  outdoor_p0_auc_test outdoor_p1_auc_test indoor_avg_acc_val  \
0         0.947(0.02)         0.964(0.03)        0.856(0.02)   
0         0.944(0.02)         0.964(0.01)        0.840(0.01)   

  indoor_avg_auc_val outdoor_avg_acc_val outdoor_avg_auc_val  \
0        0.941(0.01)         0.871(0.03)         0.957(0.01)   
0        0.942(0.01)         0.860(0.03)         0.955(0.01)   

  indoor_avg_acc_test indoor_avg_auc_test outdoor_avg_acc_test  \
0         0.843(0.04)         0.927(0.03)          0.865(0.01)   
0         0.850(0.01)         0.943(0.02)          0.865(0.01)   

  outdoor_avg_auc_test avg_minorirty_acc_val avg_minorirty_auc_val  \
0          0.956(0.00)           0.000(0.00)           0.000(0.00)   
0          0.954(0.00)           0.000(0.00)           0.000(0.00)   

  avg_minorirty_acc_test avg_minorirty_auc_test  avg_acc_val  avg_auc_val  \
0            0.000(0.00)            0.000(0.00)  0.864(0.02)  0.949(0.01)   
0            0.000(0.00)            0.000(0.00)  0.849(0.01)  0.948(0.00)   

  avg_acc_test avg_auc_test  
0  0.854(0.02)  0.941(0.01)  
0  0.857(0.01)  0.949(0.01)